stages:
  - test
  - build
  - deploy

# =========================
# GLOBAL CONFIG
# =========================

default:
  image: docker:24.0.5-cli

  services:
    - name: docker:24.0.5-dind
      command:
        - "--host=tcp://0.0.0.0:2375"
        - "--tls=false"
        - "--insecure-registry=192.168.0.147:5050"

  before_script:
    - docker info
    - unset DOCKER_TLS_VERIFY
    - export DOCKER_CONFIG=/tmp/docker-config
    - mkdir -p $DOCKER_CONFIG

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  CI_REGISTRY: "192.168.0.147:5050"
  CI_REGISTRY_IMAGE_BACKEND: "$CI_REGISTRY/root/$CI_PROJECT_NAME/backend"
  CI_REGISTRY_IMAGE_FRONTEND: "$CI_REGISTRY/root/$CI_PROJECT_NAME/frontend"

cache:
  paths:
    - frontend/node_modules/
    - backend/__pycache__/

# =========================
# TEST
# =========================

test-backend:
  stage: test
  image: python:3.12-slim

  before_script:
    - pip install flake8 pytest
    - pip install -r backend/requirements.txt

  script:
    - flake8 backend/ --max-line-length=120
    - cd backend
    - python -m pytest || echo "No tests"

  only:
    - main
    - merge_requests


test-frontend:
  stage: test
  image: node:18-alpine

  script:
    - cd frontend
    - npm install
    - npm run lint || echo "No linter"

  only:
    - main
    - merge_requests

# =========================
# BUILD BACKEND
# =========================

build-backend:
  stage: build

  before_script:
    - unset DOCKER_TLS_VERIFY
    - echo "$MY_REGISTRY_TOKEN" | docker login 192.168.0.147:5050 -u git --password-stdin

  script:
    - docker build -t $CI_REGISTRY_IMAGE_BACKEND:$CI_COMMIT_SHORT_SHA ./backend
    - docker tag $CI_REGISTRY_IMAGE_BACKEND:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE_BACKEND:latest

    - docker push $CI_REGISTRY_IMAGE_BACKEND:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE_BACKEND:latest

  only:
    - main


# =========================
# BUILD FRONTEND
# =========================

build-frontend:
  stage: build

  before_script:
    - unset DOCKER_TLS_VERIFY
    - echo "$MY_REGISTRY_TOKEN" | docker login 192.168.0.147:5050 -u git --password-stdin

  script:
    - docker build -t $CI_REGISTRY_IMAGE_FRONTEND:$CI_COMMIT_SHORT_SHA ./frontend
    - docker tag $CI_REGISTRY_IMAGE_FRONTEND:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE_FRONTEND:latest

    - docker push $CI_REGISTRY_IMAGE_FRONTEND:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE_FRONTEND:latest

  only:
    - main

# =========================
# DEPLOY
# =========================

deploy:
  stage: deploy
  image: alpine:latest

  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)

    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts

  script:
    - |
      ssh $SSH_USER@$PROD_SERVER "
        echo '$MY_REGISTRY_TOKEN' | docker login 192.168.0.147:5050 -u git --password-stdin &&
        cd /home/$SSH_USER/project &&
        docker compose pull &&
        docker compose up -d &&
        docker image prune -f
      "

  environment:
    name: production
    url: http://$PROD_SERVER

  only:
    - main
